In [2]:
import os
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
import pickle

df = pd.read_csv('coconut.csv')
df.head()

Month  Year  Rainfall   WPI
0      4  2012      47.5  84.3
1      5  2012      31.7  79.5
2      6  2012     117.8  80.2
3      7  2012     250.2  78.8
4      8  2012     262.4  78.1

In [4]:
X = df.iloc[:, :-1].values
Y = df.iloc[:, 3].values

param_grid = {'bootstrap': [True], 
              'max_depth': [5, 7, 10, None], 
              'max_features': ['auto', 'log2'], 
              'n_estimators': [5, 6, 7, 8, 9, 10, 11, 12, 13, 15]
             }

In [6]:
rfr = RandomForestRegressor(random_state = 1)

g_search = GridSearchCV(estimator = rfr, param_grid = param_grid, 

                          cv = 4, n_jobs = -1, verbose = 0, return_train_score=True)
g_search.fit(X, Y)

/usr/local/lib/python3.9/dist-packages/sklearn/ensemble/_forest.py:413: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features=1.0` or remove this parameter as it is also the default value for RandomForestRegressors and ExtraTreesRegressors.
  warn(


GridSearchCV(cv=4, estimator=RandomForestRegressor(random_state=1), n_jobs=-1,
             param_grid={'bootstrap': [True], 'max_depth': [5, 7, 10, None],
                         'max_features': ['auto', 'log2'],
                         'n_estimators': [5, 6, 7, 8, 9, 10, 11, 12, 13, 15]},
             return_train_score=True)

In [8]:
print(g_search.best_params_)
print(g_search.best_score_)

{'bootstrap': True, 'max_depth': 5, 'max_features': 'auto', 'n_estimators': 13}
-14.842653794484113


In [10]:
rfr = RandomForestRegressor(random_state = 1, max_depth = 5, max_features = 'auto', n_estimators = 13)
rfr.fit(X, Y)

x = [5, 2012, 31.7]
rfr.predict(np.array(x).reshape(1, -1))

/usr/local/lib/python3.9/dist-packages/sklearn/ensemble/_forest.py:413: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features=1.0` or remove this parameter as it is also the default value for RandomForestRegressors and ExtraTreesRegressors.
  warn(


array([80.39156593])

In [11]:
pickle.dump(rfr, open('../coconut_price_prediction.pkl', "wb"))

**Cotton Model Training**

In [13]:
df = pd.read_csv('Cotton.csv')
df.head()

X = df.iloc[:, :-1].values
Y = df.iloc[:, 3].values

param_grid = {'bootstrap': [True], 
              'max_depth': [5, 7, 10, None], 
              'max_features': ['auto', 'log2'], 
              'n_estimators': [5, 6, 7, 8, 9, 10, 11, 12, 13, 15]
             }
rfr = RandomForestRegressor(random_state = 1)

g_search = GridSearchCV(estimator = rfr, param_grid = param_grid, 

                          cv = 4, n_jobs = -1, verbose = 0, return_train_score=True)
g_search.fit(X, Y)

print(g_search.best_params_)
print(g_search.best_score_)

{'bootstrap': True, 'max_depth': 5, 'max_features': 'log2', 'n_estimators': 15}
-9.261141444122277


In [15]:
rfr = RandomForestRegressor(random_state = 1, max_depth = 5, max_features = 'log2', n_estimators = 15)
rfr.fit(X, Y)

x = [5, 2018, 31.7]
rfr.predict(np.array(x).reshape(1, -1))

array([137.66575896])

In [16]:
pickle.dump(rfr, open('../cotton_price_prediction.pkl', "wb"))

**Gram Model Training**

In [17]:
df = pd.read_csv('Gram.csv')
df.head()

X = df.iloc[:, :-1].values
Y = df.iloc[:, 3].values

param_grid = {'bootstrap': [True], 
              'max_depth': [5, 7, 10, None], 
              'max_features': ['auto', 'log2'], 
              'n_estimators': [5, 6, 7, 8, 9, 10, 11, 12, 13, 15]
             }
rfr = RandomForestRegressor(random_state = 1)

g_search = GridSearchCV(estimator = rfr, param_grid = param_grid, 

                          cv = 4, n_jobs = -1, verbose = 0, return_train_score=True)
g_search.fit(X, Y)

print(g_search.best_params_)
print(g_search.best_score_)

{'bootstrap': True, 'max_depth': 10, 'max_features': 'log2', 'n_estimators': 15}
-2.9667390638268367


In [18]:
rfr = RandomForestRegressor(random_state = 1, max_depth = 10, max_features = 'log2', n_estimators = 15)
rfr.fit(X, Y)

x = [5, 2018, 31.7]
rfr.predict(np.array(x).reshape(1, -1))

array([141.73111111])

In [19]:
pickle.dump(rfr, open('../black_gram_price_prediction.pkl', "wb"))

**Jute Model Training**

In [21]:
df = pd.read_csv('Jute.csv')
df.head()

X = df.iloc[:, :-1].values
Y = df.iloc[:, 3].values

param_grid = {'bootstrap': [True], 
              'max_depth': [5, 7, 10, None], 
              'max_features': ['auto', 'log2'], 
              'n_estimators': [5, 6, 7, 8, 9, 10, 11, 12, 13, 15]
             }
rfr = RandomForestRegressor(random_state = 1)

g_search = GridSearchCV(estimator = rfr, param_grid = param_grid, 

                          cv = 4, n_jobs = -1, verbose = 0, return_train_score=True)
g_search.fit(X, Y)

print(g_search.best_params_)
print(g_search.best_score_)

{'bootstrap': True, 'max_depth': 10, 'max_features': 'log2', 'n_estimators': 12}
-6.651851338952283


In [22]:
rfr = RandomForestRegressor(random_state = 1, max_depth = 10, max_features = 'log2', n_estimators = 12)
rfr.fit(X, Y)

x = [5, 2018, 31.7]
rfr.predict(np.array(x).reshape(1, -1))

array([166.855])

In [24]:
pickle.dump(rfr, open('../jute_price_prediction.pkl', "wb"))

**Maize Model Training**

In [26]:
df = pd.read_csv('Maize.csv')
df.head()

X = df.iloc[:, :-1].values
Y = df.iloc[:, 3].values

param_grid = {'bootstrap': [True], 
              'max_depth': [5, 7, 10, None], 
              'max_features': ['auto', 'log2'], 
              'n_estimators': [5, 6, 7, 8, 9, 10, 11, 12, 13, 15]
             }
rfr = RandomForestRegressor(random_state = 1)

g_search = GridSearchCV(estimator = rfr, param_grid = param_grid, 

                          cv = 4, n_jobs = -1, verbose = 0, return_train_score=True)
g_search.fit(X, Y)

print(g_search.best_params_)
print(g_search.best_score_)

{'bootstrap': True, 'max_depth': 5, 'max_features': 'auto', 'n_estimators': 15}
-3.4795911589670245


/usr/local/lib/python3.9/dist-packages/sklearn/ensemble/_forest.py:413: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features=1.0` or remove this parameter as it is also the default value for RandomForestRegressors and ExtraTreesRegressors.
  warn(


In [27]:
rfr = RandomForestRegressor(random_state = 1, max_depth = 5, max_features = 'auto', n_estimators = 15)
rfr.fit(X, Y)

x = [5, 2018, 31.7]
rfr.predict(np.array(x).reshape(1, -1))

/usr/local/lib/python3.9/dist-packages/sklearn/ensemble/_forest.py:413: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features=1.0` or remove this parameter as it is also the default value for RandomForestRegressors and ExtraTreesRegressors.
  warn(


array([117.58527778])

In [28]:
pickle.dump(rfr, open('../maize_price_prediction.pkl', "wb"))

**Moong Model Training**

In [29]:
df = pd.read_csv('Moong.csv')
df.head()

X = df.iloc[:, :-1].values
Y = df.iloc[:, 3].values

param_grid = {'bootstrap': [True], 
              'max_depth': [5, 7, 10, None], 
              'max_features': ['auto', 'log2'], 
              'n_estimators': [5, 6, 7, 8, 9, 10, 11, 12, 13, 15]
             }
rfr = RandomForestRegressor(random_state = 1)

g_search = GridSearchCV(estimator = rfr, param_grid = param_grid, 

                          cv = 4, n_jobs = -1, verbose = 0, return_train_score=True)
g_search.fit(X, Y)

print(g_search.best_params_)
print(g_search.best_score_)

{'bootstrap': True, 'max_depth': 5, 'max_features': 'auto', 'n_estimators': 5}
-2.5871558752251396


/usr/local/lib/python3.9/dist-packages/sklearn/ensemble/_forest.py:413: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features=1.0` or remove this parameter as it is also the default value for RandomForestRegressors and ExtraTreesRegressors.
  warn(


In [30]:
rfr = RandomForestRegressor(random_state = 1, max_depth = 5, max_features = 'auto', n_estimators = 5)
rfr.fit(X, Y)

x = [12, 2018, 35]
rfr.predict(np.array(x).reshape(1, -1))

/usr/local/lib/python3.9/dist-packages/sklearn/ensemble/_forest.py:413: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features=1.0` or remove this parameter as it is also the default value for RandomForestRegressors and ExtraTreesRegressors.
  warn(


array([117.64])

In [31]:
pickle.dump(rfr, open('../moong_price_prediction.pkl', "wb"))